version: 1.0.0.{build}
image: Visual Studio 2019 Preview
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- ps: dotnet restore
after_build:
- ps: dotnet pack -c release -p:PackageVersion=3.3.3-beta
build:
  verbosity: minimal
  publish_nuget: true
test_script:
- ps: dotnet test .\MXLoggerTest\MXLoggerTest.csproj
nuget:
  account_feed: false
  project_feed: true
  disable_publish_on_pr: true
artifacts:
- path: '**\*.nupkg'
