name: .NET Build & Test

on:
  push:
   branches:
    - '**'
  pull_request:
  workflow_dispatch:  # enable manual runs
  workflow_call:  # allows other workflows to call this one  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: "10.0.x"

    - name: Restore dependencies
      run: dotnet restore MXLogger.slnx

    - name: Build solution
      run: dotnet build MXLogger.slnx --configuration Release --no-restore

    - name: Run all tests
      run: dotnet test ExchangeTime.sln --configuration Release
